import { expect, test } from 'vitest';
import { separateSyllables } from '../src/lib/syllables';

test('separate syllables', () => {
  const table: Array<[string, string[]]> = [
    ['casa', ['ca', 'sa']],
    ['amigo', ['a', 'mi', 'go']],
    ['camisa', ['ca', 'mi', 'sa']],
    ['casaco', ['ca', 'sa', 'co']],
    ['dezena', ['de', 'ze', 'na']],
    ['faca', ['fa', 'ca']],
    ['fogo', ['fo', 'go']],
    ['fibra', ['fi', 'bra']],
    ['flor', ['flor']],
    ['teclado', ['te', 'cla', 'do']],
    ['frio', ['fri', 'o']],
    ['geada', ['ge', 'a', 'da']],
    ['desafio', ['de', 'sa', 'fi', 'o']],
    ['bajular', ['ba', 'ju', 'lar']],
    ['guiar', ['gui', 'ar']],
    ['guiado', ['gui', 'a', 'do']],
    ['guia', ['gui', 'a']],
    ['guerra', ['guer', 'ra']],
    ['barraca', ['bar', 'ra', 'ca']],
    ['barracão', ['bar', 'ra', 'cão']],
    ['guarda', ['guar', 'da']],
    ['barco', ['bar', 'co']],
    ['amassar', ['a', 'mas', 'sar']],
    ['terra', ['ter', 'ra']],
    ['terreno', ['ter', 're', 'no']],
    ['cetíco', ['ce', 'tí', 'co']],
    ['privacidade', ['pri', 'va', 'ci', 'da', 'de']],
    ['privado', ['pri', 'va', 'do']],
    ['privar', ['pri', 'var']],
    ['furtado', ['fur', 'ta', 'do']],
    ['barriga', ['bar', 'ri', 'ga']],
    ['projeto', ['pro', 'je', 'to']],
    ['armado', ['ar', 'ma', 'do']],
    ['passo', ['pas', 'so']],
    ['passado', ['pas', 'sa', 'do']],
    ['hoje', ['ho', 'je']],
    ['chama', ['cha', 'ma']],
    ['fachada', ['fa', 'cha', 'da']],
    ['armadilha', ['ar', 'ma', 'di', 'lha']],
    ['pilha', ['pi', 'lha']],
    ['palha', ['pa', 'lha']],
    ['canhão', ['ca', 'nhão']],
    ['canhoto', ['ca', 'nho', 'to']],
    ['escrever', ['es', 'cre', 'ver']],
    ['capitão', ['ca', 'pi', 'tão']],
    // ['incrível', ['in', 'crí', 'vel']],
    // ['tênis', ['tê', 'nis']],
    // ['bateria', ['ba', 'te', 'ri', 'a']],
    // ['dois', ['dois']],
    // ['explorar', ['ex', 'plo', 'rar']],
    // ['zero', ['ze', 'ro']],
    // ['dormitório', ['dor', 'mi', 'tó', 'rio']],
    // ['elefante', ['e', 'le', 'fan', 'te']],
    // ['fonte', ['fon', 'te']],
    // ['engatinhar', ['en', 'ga', 'ti', 'nhar']],
    // ['cambalhota', ['cam', 'ba', 'lho', 'ta']],
    // ['abóbora', ['a', 'bó', 'bo', 'ra']],
    // ['direita', ['di', 'rei', 'ta']],
    // ['esquerda', ['es', 'quer', 'da']],
    // ['caixão', ['cai', 'xão']],
    // ['dinheiro', ['di', 'nhei', 'ro']],
    // ['aposento', ['a', 'po', 'sen', 'to']],
    // ['feira', ['fei', 'ra']],
    // ['palco', ['pal', 'co']],
    // ['sisterna', ['cis', 'ter', 'na']],
    // ['silva', ['sil', 'va']],
    // ['pastel', ['pas', 'tel']],
    // ['ontem', ['on', 'tem']],
    // ['folheto', ['fo', 'lhe', 'to']],
    // ['passagem', ['pas', 'sa', 'gem']],
    // ['apostar', ['a', 'pos', 'tar']],
    // ['pista', ['pis', 'ta']],
    // ['quinze', ['quin', 'ze']],
    // ['fúria', ['fú', 'ri', 'a']],
    // ['festa', ['fes', 'ta']],
    // ['cetim', ['ce', 'tim']],
    // ['adiante', ['a', 'di', 'an', 'te']],
    // ['fogueira', ['fo', 'guei', 'ra']],
    // ['dente', ['den', 'te']],
    // ['adeus', ['a', 'deus']],
    // ['pneumonia', ['pneu', 'mo', 'ni', 'a']],
    // ['computador', ['com', 'pu', 'ta', 'dor']],
    // ['adelante', ['a', 'de', 'lan', 'te']],
    // ['cadeira', ['ca', 'dei', 'ra']],
  ];

  table.forEach(([word, syllables]) => {
    expect(separateSyllables(word)).toEqual(syllables);
  });
});
